default:
  tags:
    - self-hosted
  image: node:20.12.2

stages:
  - prepare
  - lint
  - build

prepare:
  stage: prepare

  cache:
    key:
      files:
        - package-lock.json
        - package.json
      prefix: ${CI_PROJECT_NAME}
    paths:
      - node_modules/
  script:
    - "npm ci"

lint:
  stage: lint
  dependencies:
    - prepare
  script:
    - "npm run lint"

build:
  stage: build
  dependencies:
    - prepare
  script:
    - "npm run build"
