version: "3.8"

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  next:
    image: anthill-v2
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    ports:
      - 8080:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/antnest?schema=public

volumes:
  postgres:
